// Frontend contract for the wallet domain. Backend source of truth:
// - App\Http\Resources\WalletTransactionResource (transaction shape)
// - App\Http\Controllers\WalletController (per-page props shape)
// - App\Enums\WalletTransactionType (the union below mirrors this enum)

import type { Paginator } from './listings';
import type { GameId } from '@/config/games';

// Mirror of App\Enums\WalletTransactionType. Sign convention applied at the
// service layer:
//   Deposit / EscrowRelease / Payout / Fee → positive `amount`
//   Withdrawal / EscrowHold                → negative `amount`
export type WalletTransactionType =
    | 'deposit'
    | 'withdrawal'
    | 'escrow_hold'
    | 'escrow_release'
    | 'payout'
    | 'fee';

// Embedded preview of the related listing (when the ledger row references one).
// `null` for deposits / withdrawals / fees that aren't tied to a listing.
export interface RelatedListingSummary {
    id: number;
    game: GameId;
}

// Embedded match summary for transactions whose listing has a 1:1 match
// (Payout / Fee, and any Hold posted at match-take). The frontend uses this
// to deep-link Payout / Fee rows directly to the match.
export interface RelatedMatchSummary {
    id: number;
}

export interface WalletTransaction {
    id: number;
    type: WalletTransactionType;
    // Signed: positive = credit, negative = debit. Cast from the backend's
    // BCMath string at the resource boundary; safe to format with .toFixed(2)
    // for display.
    amount: number;
    balance_after: number;
    related_listing_id: number | null;
    // Eager-loaded summary. Always present on index + history pages; `null`
    // when the transaction has no related listing.
    related_listing: RelatedListingSummary | null;
    // Eager-loaded summary of the listing's match, when one exists. `null`
    // for transactions on listings that were cancelled / expired before
    // anyone took them.
    related_match: RelatedMatchSummary | null;
    description: string | null;
    created_at: string | null;
}

export interface WalletFilters {
    type: WalletTransactionType | null;
}

// /wallet — overview page (balance + actions + last 5 transactions).
// `recentTransactions` is a resource collection without pagination meta
// (controller calls `->get()`, not `->paginate()`).
export interface WalletIndexProps {
    balance: number;
    recentTransactions: { data: WalletTransaction[] };
}

// /wallet/deposit — shows the user's TRC20 address + QR code.
// Address is a v1 mock generated by `App\Support\MockTronAddress`; real
// HD-derived addresses replace these at the pre-launch chain integration gate.
export interface WalletDepositProps {
    tronAddress: string;
}

// /wallet/withdraw — form page. `minWithdrawal` is sourced from
// `WithdrawRequest::MIN_WITHDRAWAL` so the frontend never duplicates the
// constant.
export interface WalletWithdrawProps {
    balance: number;
    minWithdrawal: number;
}

// /wallet/history — paginated ledger view with `?filter[type]=` chip filter.
// `types` carries all enum values so the chip row can render without
// hardcoding the list on the frontend.
export interface WalletHistoryProps {
    transactions: Paginator<WalletTransaction>;
    filters: WalletFilters;
    types: WalletTransactionType[];
}
